name: app_develop
description: "A new Flutter project."
publish_to: 'none'  # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  material_design_icons_flutter: ^7.0.7296
  flutter_screenutil: ^5.5.1
  font_awesome_flutter: ^10.2.0  # Add Font Awesome dependency here
  hugeicons: ^0.0.1
  http: ^1.3.0  # Add the http package for network requests
  google_maps_flutter: ^2.5.0
  geolocator: ^13.0.2
  image_picker: ^1.1.2 # Use the latest version
  carousel_slider: ^5.0.0
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.5.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
