name: app_develop
description: "A new Flutter project."
publish_to: 'none'  # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  material_design_icons_flutter: ^5.0.6595
  flutter_screenutil: ^5.5.1
  font_awesome_flutter: ^10.2.0  # Add Font Awesome dependency here
  hugeicons: ^0.0.1
  http: ^1.1.0
  google_maps_flutter: ^2.5.3
  image_picker: ^0.8.7+4 # Use the latest version
  location: ^5.0.3
  geolocator: ^10.1.0
  provider: ^6.1.1
  flutter_config: ^2.0.2
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
